Add support for repos where the CI workflow is named `ci.yaml`
alphagov/govuk-saas-config pull request #141
Opened 2023-03-02 17:04 UTC by robinjam

(Blocked until #140 is merged)

Currently this script sets up required status checks if the CI workflow is named exactly `ci.yml` (and not `ci.yaml` as it’s named on [7 of our repos](https://github.com/search?q=org%3Aalphagov+path%3A.github%2Fworkflows%2Fci.yaml&type=code)).

This PR adds support for repos where the workflow is named `ci.yaml`.

Before merging, it might be a good idea to give the owners of the 7 aforementioned repos a heads-up, as this will change the required status checks for their repos.

2023-03-03 06:42 UTC, ChrisBAshton requested changes
Good spot!

But I think the correct fix is to rename the `ci.yaml` file to `ci.yml` in the 7 repos affected, rather than build in extra complexity here. Especially if there'd be some outreach required for this change - we may as well make "renaming the file" the outreach action, if that makes sense 😄

2023-03-06 09:54 UTC, robinjam commented
I'm happy to go down that route (given the developer docs recommend naming the file `ci.yml`), but it does concern me that we weren't alerted about the mismatch, and that folks might name their workflows `ci.yaml` when they create new repos/add GH actions to existing repos moving forward (especially given that's [the recommended extension](https://yaml.org/faq.html) for YAML files).

2023-03-06 10:53 UTC, closed without merging

2023-03-08 09:52 UTC, ChrisBAshton commented
@robinjam that's a good point about there being no alerting - perhaps we could build something into govuk-saas-config that checks for a `ci.yaml` file and alerts a Slack channel (or at least logs something).

There's certainly an argument to change the recommendation to ci.yaml [in the dev docs](https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-with-github-actions.html). I imagine `yml` was chosen because that's the file extension used in Rails i18n, among other things, so is a de facto standard if not an official one. Consistent naming across our repos is probably the most important consideration though.

2023-03-08 10:14 UTC, robinjam commented
Oh I don't think it's necessary to change the recommendation in the dev docs, that would just create unnecessary toil 😅

I'm taking a look through the affected repos and will raise PRs if appropriate (i.e. if the repo is tagged "govuk", isn't archived, the workflow is named `ci.yaml`, and it contains a test job). Already done `bulk-changer`.